### ISSUE TITLE
Render components on server too for SSR

### ISSUE THREAD

**Issue by SachaG** [Meteor-Alt/accounts#2]
We probably should avoid using the `/client` folder?

**Comment by SachaG** [comment]
awesome :)

**Comment by SachaG** [comment]
Actually, this works as far as not triggering the error, but the component is still not rendered server-side. I don't know how easy it would be to actually do this though, as some of Meteor's own APIs are only available client-side…

**Comment by emmostrom** [comment]
I don't think anything is really gained by having the login completely render on the server and would add to the complexity.  Most SSR is for search engine cache or to make the page render before everything is ready... Neither really apply for login.

**Comment by SachaG** [comment]
Maybe you're right. It's just visually jarring to have the log in button pop in after a delay when you first load the site. Maybe as a compromise only the button could be server-side rendered?

**Comment by emmostrom** [comment]
OK changed it to actually render the component server side in 1.1.0
